import type { NPC } from '../state'

export const SEED_NPCS: NPC[] = [
  {
    id: 'brent-schellenbarger',
    name: 'Brent Schellenbarger',
    vibe: 'Self-promoter. Posts velocity screenshots in #general. Has a personal dashboard.',
    approveRatePerMin: 2.5,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'chip-mittelbach',
    name: 'Chip Mittelbach',
    vibe: 'LGTM machine. Has never left a comment. Somehow #1 every quarter.',
    approveRatePerMin: 3.3,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'dwayne-krebsbach',
    name: 'Dwayne Krebsbach',
    vibe: 'Reviews everything in under 4 seconds. Considers this a feature.',
    approveRatePerMin: 3.7,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'rhonda-papadimitriou',
    name: 'Rhonda Papadimitriou',
    vibe: 'Steady. Actually reads the diffs. Keeps a spreadsheet of her error catch rate.',
    approveRatePerMin: 1.7,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'skyler-tinklenberg',
    name: 'Skyler Tinklenberg',
    vibe: 'Joined 3 weeks ago. Approving everything to seem collaborative.',
    approveRatePerMin: 2.8,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'brett-fusselman',
    name: 'Brett Fusselman',
    vibe: '"Just ship it." Has this as a Teams status message.',
    approveRatePerMin: 3.1,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'dax-cornthwaite',
    name: 'Dax Cornthwaite',
    vibe: 'Runs a script that auto-approves anything with "chore" in the title.',
    approveRatePerMin: 2.2,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'kip-schlueter',
    name: 'Kip Schlueter',
    vibe: 'Slow staff eng. Leaves 12-comment reviews. The Bobs love him.',
    approveRatePerMin: 0.7,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'garrett-winklebauer',
    name: 'Garrett Winklebauer',
    vibe: 'Approves PRs from his phone during standup.',
    approveRatePerMin: 2.6,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'craig-pumphrey',
    name: 'Craig Pumphrey',
    vibe: 'Principal engineer. Theoretically reviews things. Actually on a podcast circuit.',
    approveRatePerMin: 1.0,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'marcy-thistlewaite',
    name: 'Marcy Thistlewaite',
    vibe: 'Sends "LGTM! Great work as always :)" on every PR. Has a macro for it.',
    approveRatePerMin: 3.6,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'glen-butterworth',
    name: 'Glen Butterworth',
    vibe: 'On PTO. Still somehow approving things.',
    approveRatePerMin: 2.0,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'doug-floomph',
    name: 'Doug Floomph',
    vibe: 'Engineering manager who "keeps his hand in the code." No one has asked him to.',
    approveRatePerMin: 1.6,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'russ-vanderhoeven',
    name: 'Russ Vanderhoeven',
    vibe: 'Approves based on commit message length. Shorter = more confident.',
    approveRatePerMin: 2.4,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'brittany-schlotterbeck',
    name: 'Brittany Schlotterbeck',
    vibe: 'Just got her H1B renewed. Not taking any risks.',
    approveRatePerMin: 2.1,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'norm-plunkettforth',
    name: 'Norm Plunkettforth',
    vibe: 'Former FAANG. Has mentioned this twice today already.',
    approveRatePerMin: 1.4,
    approves: 0,
    active: true,
    laidOff: false,
  },
  {
    id: 'engineer-9000',
    name: 'Brad++ 🤖',
    vibe: 'Deployed at 08:02:30. Does not sleep. Does not eat. Does not review.',
    approveRatePerMin: 5.0,
    approves: 0,
    active: false,
    laidOff: false,
  },
]
