import type { SlackMessage } from '../state'

export const ALL_SLACK: SlackMessage[] = [
  {
    id: 'slack-001',
    spawnAt: 0,
    channel: '#eng-general',
    sender: 'brad',
    body: 'gm everyone 🚀 already at 3 approvals for today, who else is grinding?',
    prefersUrgent: false,
  },
  {
    id: 'slack-002',
    spawnAt: 15000,
    channel: '#eng-general',
    sender: 'chad',
    body: 'LGTM machine is online 🤖',
    prefersUrgent: false,
  },
  {
    id: 'slack-003',
    spawnAt: 30000,
    channel: '#random',
    sender: 'tanvi',
    body: 'does anyone know why the build takes 12 minutes now? asking for a friend (the friend is me)',
    prefersUrgent: false,
  },
  {
    id: 'slack-004',
    spawnAt: 90000,
    channel: 'DM: Brad',
    sender: 'brad',
    body: 'yo 👀 how many PRs you at?',
    prefersUrgent: false,
  },
  {
    id: 'slack-005',
    spawnAt: 120000,
    channel: '#eng-general',
    sender: 'brad',
    body: 'friendly reminder that calibration is TODAY. velocity numbers are visible to mgmt. just saying 🙂',
    prefersUrgent: false,
  },
  {
    id: 'slack-006',
    spawnAt: 180000,
    channel: '#random',
    sender: 'karen_staffeng',
    body: 'reminder: please actually read the diffs before approving. we had two incidents last quarter from rubber-stamped dependency bumps',
    prefersUrgent: false,
  },
  {
    id: 'slack-007',
    spawnAt: 210000,
    channel: '#growth-launch',
    sender: 'growth-pm',
    body: 'hey team the pricing page PR is blocking our launch window, can someone LGTM real quick? it\'s literally just a feature flag 🙏',
    prefersUrgent: true,
  },
  {
    id: 'slack-008',
    spawnAt: 240000,
    channel: '#growth-launch',
    sender: 'brad',
    body: 'approved 👍 LGTM',
    prefersUrgent: false,
  },
  {
    id: 'slack-009',
    spawnAt: 270000,
    channel: '#eng-general',
    sender: 'devx-bot',
    body: '[Brad++ 🤖] I have processed 47 pull requests in the last 30 minutes. My throughput is optimal. Organic engineers are encouraged to maintain competitive velocity.',
    prefersUrgent: false,
  },
  {
    id: 'slack-010',
    spawnAt: 300000,
    channel: '#random',
    sender: 'brad',
    body: 'lol engineer 9000 is going to get us all laid off 😬',
    prefersUrgent: false,
  },
  {
    id: 'slack-011',
    spawnAt: 360000,
    channel: 'DM: Manager',
    sender: 'bill_lumbergh',
    body: 'Yeaaaah, so I\'m going to need you to go ahead and clear that queue by EOD. We have calibration this afternoon and it\'d be reaaally great if the velocity numbers looked good. Mmmkay?',
    prefersUrgent: false,
  },
  {
    id: 'slack-012',
    spawnAt: 400000,
    channel: '#eng-general',
    sender: 'tanvi',
    body: 'heads up: I\'m seeing some weird npm registry behavior on a few of our deps. anyone else notice anything? probably nothing but...',
    prefersUrgent: false,
  },
  {
    id: 'slack-013',
    spawnAt: 430000,
    channel: '#eng-general',
    sender: 'chad',
    body: 'tanvi stop overthinking lol, dependabot auto-bumps are always safe',
    prefersUrgent: false,
  },
  {
    id: 'slack-014',
    spawnAt: 460000,
    channel: '#random',
    sender: 'brad',
    body: 'today\'s score: Brad 14, Brad++ 🤖 67, everyone else lmao',
    prefersUrgent: false,
  },
]
